### ISSUE TITLE
v2.0 Roadmap

### ISSUE THREAD

**Issue by pzuraq** [ember-decorators/ember-decorators#186]
Opening this issue to record the future plans for this library, and what v2 is going to look like from a high level. I don't think we should fully finalize anything until TC39 advances decorators to stage 3 and Babel and Typescript have implemented the new standard, but that could be a ways off as is (hopefully the January meeting).

## Major Changes

- [ ] Break out all decorators into individual packages. Decorators should be imported from the `@ember-decorators` scope, and each sub-package should be its own addon. We can begin breaking these packages out immediately since they will be in their own addons, and can publish them separately as pre-1.0 (or pre-2.0, if we want to lock-step) packages until we're ready to ship v2.0 of the base library. The packages to break out are:
  - [ ] `@ember-decorators/component` - [repo](https://github.com/ember-decorators/component)
    - Note: `@className` and `@attribute` currently pull the value from initializers and assign it on the prototype. This is broken behavior that will not work in the future versions of decorators, so we should _just_ add the bindings to `classNameBindings` and `attributeBindings` and not manipulate the prototype at all.
  - [ ] `@ember-decorators/controller` - [repo](https://github.com/ember-decorators/controller)
  - [x] `@ember-decorators/data` - [repo](https://github.com/ember-decorators/data)
  - [x] `@ember-decorators/object` - [repo](https://github.com/ember-decorators/object)
  - [ ] `@ember-decorators/service` - [repo](https://github.com/ember-decorators/service)
- [ ] Drop support for use in POJOs, following the spec decorators will only be usable in classes. We should drop support and update all tests to reflect this.
- [ ] ~Upgrade to Babel 7, drop Babel 6 support (unless the decorators spec is backwards compatible between stages 1-3, or backwards compatibility is trivial)~ We're going to wait until v3 to do this since the transforms just haven't been happening, blocked on TC39 acceptance
- [ ] Add Typescript support
- [x] Remove babel transforms and instead add `@ember-decorators/babel-transforms` via the default blueprint
- [x] Drop deprecations
  - [x] Remove old computed style in favor of `@ember-decorators/auto-computed`

## Minor Changes

- [ ] Refactor utils. @buschtoens has started this process by breaking them out into a separate repository, but I think we should try to revisit the existing helper functions and see if we can make them more reusable. The fact that we have so many different "macro" functions is a code smell to me.

**Comment by snewcomer** [comment]
@pzuraq Awesome roadmap! Does this include the runloop decorators as well?  #179

**Comment by pzuraq** [comment]
We can start experimenting with them in their own addon/package now too, I think it would be good to solidify them and make sure they make sense and aren't confusing before shipping them with the base package by default.
